<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
	  <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
	  <PackageReference Include="Google.Apis.Drive.v3" Version="1.75.0.4192" />
	  <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ASF.Core\ASF.Core.csproj" />
    <ProjectReference Include="..\ASF.Repository\ASF.Repository.csproj" />
  </ItemGroup>

</Project>
